type BanterType = "carry" | "roast";

const CARRY_LINES = [
  "{name} carried harder than a shopping bag",
  "{name} turned the server into a highlight reel",
  "The other team is still looking for {name}",
  "{name} chose violence today",
  "Rename the match to the {name} show",
  "{name} made the whole lobby question their rank",
  "{name} just put that on the resume",
  "{name} was playing a different game than everyone else",
  "Someone check {name}'s gaming chair",
  "{name} went full action movie protagonist",
  "{name} didn't come to play, they came to dominate",
  "The server should thank {name} for the content",
  "{name} treated the match like aim practice",
  "{name} woke up and chose destruction",
  "{name} had the lobby on speed dial",
  "{name} hit shots like rent was due",
  "{name} left fingerprints on every round",
  "{name} was farming clips, not enemies",
  "{name} made top frag look like a birthright",
  "{name} had the crosshair on autopilot",
  "{name} spent the match collecting souls",
  "{name} was handing out one-way tickets to spawn",
  "{name} made the scoreboard look photoshopped",
  "{name} was deleting people on contact",
  "{name} ran the server like a private lobby",
  "{name} was so hot the deagle needed oven mitts",
  "{name} had everyone else queued as background actors",
  "{name} was dropping rounds into the win column by hand",
  "{name} made every duel look pre-recorded",
  "{name} was one tap away from a montage contract",
  "{name} put the lobby in a group project and did all the work",
  "{name} was speedrunning MVPs",
  "{name} turned every peek into a bad life choice",
  "{name} was making crosshair placement look like witchcraft",
  "{name} had the enemy team checking for smurfs in the ceiling",
  "{name} played that like the tutorial was for everyone else",
  "{name} was built different and the server felt it",
  "{name} turned the match into a TED talk on domination",
  "{name} had the other team writing apology letters",
  "{name} was moving like the map was designed around them",
  "{name} turned every site take into a victory lap",
  "{name} was dropping 30 bombs like it was community service",
  "{name} made the other team consider retirement",
  "{name} was playing chess while everyone else played checkers",
  "{name} had the enemy team on a first-name basis with the respawn timer",
  "{name} was out there speedrunning the highlight reel",
  "{name} made the kill feed look like a grocery list",
  "{name} turned B site into a no-fly zone",
  "{name} had a personal vendetta against the entire lobby",
  "{name} was playing like the enemy owed them money",
  "{name} had the AWP singing lullabies to the other team",
  "{name} was operating on a different ping than everyone else",
  "{name} turned mid into a one-way street",
  "{name} was collecting headshots like they were on sale",
  "{name} made clutching look casual",
  "{name} was out there giving free FPL auditions",
  "{name} had the other team calling timeout on life",
  "{name} was raining fire like a broken sprinkler",
  "{name} turned every round into a masterclass",
  "{name} had the server begging for mercy",
  "{name} was playing like the mouse had a mind of its own",
  "{name} turned the scoreboard into a biography",
  "{name} was handing out lessons nobody signed up for",
  "{name} made the AK spray look like calligraphy",
  "{name} was running through the lobby like a fire drill",
  "{name} had the other team filing insurance claims",
  "{name} was playing like they had the script",
  "{name} turned spawn to site into a speed record",
  "{name} was treating every round like match point",
  "{name} made lurking look like an art form",
  "{name} was giving the enemy a free demo review",
  "{name} had the lobby reconsidering their hobby",
  "{name} was playing like their crosshair had GPS",
  "{name} turned every retake into a content piece",
  "{name} had the other team thinking it was FPL qualifiers",
  "{name} was doing things that should require a permit",
  "{name} made the deagle look like a sniper rifle",
  "{name} was multitasking between fragging and embarrassing people",
  "{name} turned the match into a solo queue documentary",
  "{name} was playing like the server was invite-only",
  "{name} had the other team taking notes",
  "{name} was farming ADR like it was a crop",
  "{name} made utility usage look like a fireworks show",
  "{name} was running the map like they built it",
  "{name} turned every eco round into a full buy performance",
  "{name} had the lobby questioning reality",
  "{name} was making first blood look routine",
  "{name} turned flick shots into a personality trait",
  "{name} was dropping entries like a DJ drops beats",
  "{name} had the enemy team on a permanent save round",
  "{name} was playing like VAC was on holiday",
  "{name} turned every 1v3 into a 1v0",
  "{name} was making the M4 look like it had aimbot firmware",
  "{name} had the server questioning its tick rate",
  "{name} was putting on a clinic for free",
  "{name} turned the match into their personal warmup",
  "{name} was playing like the scoreboard was a leaderboard application",
  "{name} had everyone else looking like NPCs",
  "{name} was making the USP look like an endgame weapon",
  "{name} turned pistol round into a statement piece",
  "{name} was handing out exit frags like business cards",
  "{name} had the lobby wondering if this was ranked",
  "{name} was farming HLTV rating in real time",
  "{name} turned every smoke execute into a movie scene",
  "{name} was playing with that main character energy",
  "{name} had the enemy team thinking about uninstalling",
  "{name} was dropping bodies like autumn leaves",
  "{name} turned every trade kill into a highlight",
  "{name} was making the other team's economy look like a recession",
  "{name} had the AWP paying its own salary",
  "{name} was running through doors like they had room service",
  "{name} turned every rotation into a parade",
  "{name} was playing like the demo was already uploaded",
  "{name} had the other team asking for a server restart",
  "{name} was making picks look like they were scheduled",
  "{name} turned the match into a podcast episode about winning",
  "{name} was playing like the scoreboard had a minimum requirement",
  "{name} had every angle on a string",
  "{name} was treating the bomb sites like personal property",
  "{name} turned every flash into an invitation to die",
  "{name} was dropping damage like a thunderstorm",
  "{name} had the enemy side looking like a tutorial level",
  "{name} was playing like they were getting paid per kill",
  "{name} turned retakes into a solo performance",
  "{name} was making the other team's strats look like suggestions",
  "{name} had the kill feed on a subscription plan",
  "{name} was farming multikills like achievements",
  "{name} turned every push into a parade float",
  "{name} was dropping entries like it was a revolving door",
  "{name} had the enemy reading obituaries mid-match",
  "{name} was playing like the minimap was a treasure map",
  "{name} turned every defuse into a victory dance",
  "{name} was making the other team's util look decorative",
  "{name} had the server sending thank-you notes",
  "{name} was treating every round like a job interview and nailing it",
  "{name} turned every peek into a postcard",
  "{name} was playing like the whole team was one person",
  "{name} had the enemy team running out of respawns spiritually",
  "{name} was dropping rounds like an album",
  "{name} turned the scoreboard into a restraining order",
  "{name} was making spray transfers look like cursive",
  "{name} had the other team on a collective timeout",
  "{name} was playing like the map pool was their backyard",
  "{name} turned every frag into a receipt",
  "{name} was making the enemy economy look like a charity case",
  "{name} had the lobby writing fan fiction about them",
  "{name} was playing like the round timer was a suggestion",
  "{name} turned every wallbang into a telegram",
  "{name} was making the other team's positions look optional",
  "{name} had the crosshair locked like it had a mortgage",
  "{name} was farming opening duels like a morning routine",
  "{name} turned every save round into a robbery",
  "{name} was playing like the enemy bought decoy armor",
  "{name} had the server running on main character script",
  "{name} was making entries look like check-ins at a hotel",
  "{name} turned the match into a solo expedition",
  "{name} was collecting aces like stamps",
  "{name} had every round looking like a rehearsed play",
  "{name} was making the map look smaller than it is",
  "{name} turned every molly into a red carpet",
  "{name} was farming impact like it was a harvest season",
  "{name} had the other team confused about which game they queued for",
  "{name} was making the AK look like it came with a warranty",
  "{name} turned every clutch into a press conference",
  "{name} was dropping headshots like confetti",
  "{name} had the lobby refreshing the scoreboard in disbelief",
  "{name} was playing like their monitor had x-ray mode",
  "{name} turned every round win into a keynote address",
  "{name} was making the galil look like it cost $3100",
  "{name} had the other team disputing the match result mentally",
  "{name} was treating the lobby like a drive-through",
  "{name} turned rotation kills into a conveyor belt",
  "{name} was making the five-seven look like a primary weapon",
  "{name} had the enemy team rage-typing motivational quotes",
  "{name} was playing like the demo review was already posted",
  "{name} turned every save into a shopping spree",
  "{name} was collecting opening kills like morning coffee",
  "{name} had the match wrapped up before overtime was an option",
  "{name} was making the desert eagle look like it had training wheels",
  "{name} turned every nade stack into a eulogy",
  "{name} was playing like the server IP was a home address",
  "{name} had the other team considering hobbies that don't involve getting destroyed",
  "{name} was making the SG look like a cheat code",
  "{name} turned every wallbang lineup into a love letter to geometry",
  "{name} was playing like they had a subscription to the killfeed",
  "{name} had the enemy team writing their memoirs mid-match",
  "{name} was treating B apps like a personal hallway",
  "{name} turned every eco into a full send festival",
  "{name} was making spray control look like it was patched in their favor",
  "{name} had the AWP scope collecting rent from every angle",
  "{name} was playing like they had early access to the round",
  "{name} turned every flash peek into a magic trick",
  "{name} was farming KAST like it was a daily quest",
  "{name} had the other team playing like they forgot their binds",
  "{name} was making mid control look like a custody agreement",
  "{name} turned the match into a seminar on dominance",
  "{name} was dropping multi-kills like loose change",
  "{name} had every single peek looking like it was rehearsed",
  "{name} was making the MAC-10 look like an investment",
  "{name} turned every after-plant into a campfire story",
  "{name} was playing like the bomb timer was their personal clock",
  "{name} had the server running {name}'s greatest hits",
  "{name} was treating the kill feed like a blog with daily posts",
  "{name} turned every CT setup into a speed bump",
  "{name} was making the UMP look like it had premium ammo",
  "{name} had the other team alt-tabbing to check their settings",
  "{name} was playing like they were the patch notes",
  "{name} turned every eco frag into a business case",
  "{name} was collecting trade kills like punch cards",
  "{name} had every angle pre-aimed like it was a dentist appointment",
  "{name} was making the famas look like it went to finishing school",
  "{name} turned the match into a nature documentary about predators",
  "{name} was dropping damage per round like it was a salary",
  "{name} had the enemy team checking their internet connection out of hope",
  "{name} was playing like the nade lineups were tattooed on their arm",
  "{name} turned every jiggle peek into a tango",
  "{name} was making the other team's defaults look like defaults on a loan",
  "{name} had the match feeling like a private tutorial",
  "{name} was farming first kills like it was their job description",
  "{name} turned every round into a paragraph in a bestselling autobiography",
  "{name} was making counter-strafing look like ballet",
  "{name} had the server sending highlights to FACEIT's front page",
  "{name} was playing like the other team brought foam swords",
  "{name} turned every peek into a documentary frame",
  "{name} was making the P250 look like it had a scope attachment",
  "{name} had every round looking like a rehearsed TikTok",
  "{name} was treating the match like a full-time job with overtime pay",
  "{name} turned every boost spot into a throne",
  "{name} was making the CZ look like it had a salary",
  "{name} had the other team considering therapy",
  "{name} was playing like the map callouts were named after them",
  "{name} turned every defuse kit into a trophy",
  "{name} was making off-angles look like the standard",
  "{name} had the enemy buying SMGs out of surrender",
  "{name} was treating the scoreboard like a speedrun timer",
  "{name} turned every timeout into a chance for the enemy to rethink life",
  "{name} was making quick switches look choreographed",
  "{name} had the other team playing like they were spectating their own funeral",
  "{name} was farming headshot percentage like a leaderboard grind",
  "{name} turned every force buy into a statement",
  "{name} was making the MP9 look like it graduated top of its class",
  "{name} had the match feeling like an exhibition game",
  "{name} was playing like every bullet had a tracking number",
  "{name} turned every T execute into a heist movie",
  "{name} was making the enemy's util look like confetti",
  "{name} had the server lag-free but the enemy team still frozen in fear",
  "{name} was treating flanks like a commute to work",
  "{name} turned every molotov into a welcome mat",
  "{name} was making the Krieg look like it had no recoil patch notes",
  "{name} had the other team buying armor just for the placebo effect",
  "{name} was playing like the server was named after them",
  "{name} turned every trade into a promotion",
  "{name} was collecting assists like they were getting credit",
  "{name} had the match wrapped like a gift for their ego",
  "{name} was making jump shots look like peer-reviewed research",
  "{name} turned every ninja defuse attempt into a guarantee",
  "{name} was playing like they had a co-pilot in their crosshair",
  "{name} had the other team asking if this was a scrim",
  "{name} was farming clutch rounds like they planted them in spring",
  "{name} turned every smoke kill into a magic show",
  "{name} was making the enemy team's comms sound like a support group",
  "{name} had the match looking like a one-player speedrun",
  "{name} was playing like the round timer owed them seconds",
  "{name} turned every CT aggression into a war crime on the scoreboard",
  "{name} was making pre-fires look like they had insider info",
  "{name} had every duel looking like the other person forgot to show up",
  "{name} was treating the match like a highlight factory",
  "{name} turned every save kill into a bonus check",
  "{name} was making the scout look like it was worth $4750",
  "{name} had the other team's IGL questioning their career choices",
  "{name} was playing like they had a cheat sheet for every round",
  "{name} turned every anti-eco into a flex tape commercial",
  "{name} was making no-scope kills look intentional",
  "{name} had the server tick rate working overtime just for their shots",
  "{name} was treating every duel like it was for a major trophy",
  "{name} turned the other team's economy into a GoFundMe",
  "{name} was making the negev look viable",
  "{name} had the other team wishing they queued for deathmatch instead",
  "{name} was playing like every round was a trailer for a movie",
  "{name} turned every post-plant into a victory parade",
  "{name} was making the Tec-9 look like it had a scope and a silencer",
  "{name} had the match looking like a Wikipedia article about domination",
  "{name} was treating the other team like practice bots with feelings",
  "{name} turned every smoke execute into a disappearing act for the enemy",
  "{name} was making the PP-Bizon look like meta",
  "{name} had the server asking for an autograph",
  "{name} was playing like the radar was a crystal ball",
  "{name} turned every 2v5 into a fair fight",
  "{name} was making bhops look like they were in the patch notes",
  "{name} had the other team questioning if skill-based matchmaking was real",
  "{name} was treating the bomb like a personal delivery service",
  "{name} turned every whiff into a setup for the next clip",
  "{name} was making the enemy team's crosshair placement look random",
  "{name} had the match feeling like a cooking show where only they knew the recipe",
  "{name} was farming ADR like they were speedrunning a stat page",
  "{name} turned every window peek into a drive-by",
  "{name} was making the other team's timeouts look like intermissions",
  "{name} had the kill feed looking like a news ticker about one person",
  "{name} was playing like they had the round outcome pre-loaded",
  "{name} turned every entry into a door that only opens one way",
  "{name} was making the nova look like it had premium spread",
  "{name} had the other team buying helmets as emotional support",
  "{name} was treating mid-round calls like they were the IGL and the team",
  "{name} turned every knife round into a preview of coming attractions",
  "{name} was making the other team's A hold look like an open house",
  "{name} had the match feeling like a public service announcement about aim",
  "{name} was playing like the server was an episode and they were the main cast",
  "{name} turned every rotating enemy into a moving target gallery",
  "{name} was making the galil look like a flagship weapon",
  "{name} had the other team's B anchor questioning their anchor status",
  "{name} was treating every angle like they had the blueprint",
  "{name} turned every 1v1 into a formality",
  "{name} was making the M4A1-S silencer sound like a lullaby for the enemy",
  "{name} had the server thinking about promoting them to admin",
  "{name} was playing like they had infinite util and zero cooldowns",
  "{name} turned every double peek into a double funeral",
  "{name} was making the other team's smoke executes look like weather effects",
  "{name} had the match looking like it was directed by them",
  "{name} was treating the bomb sites like a buffet with all-you-can-take",
  "{name} turned every timeout into a halftime show",
  "{name} was making the enemy team's economy advisor look incompetent",
  "{name} had every round looking like the enemy forgot to buy",
  "{name} was playing like they had a subscription to the enemy's comms",
  "{name} turned every post-round into a medal ceremony",
  "{name} was making the other team's lurker look lost",
  "{name} had the server ranking them before the match was over",
  "{name} was treating every flash like a personal spotlight",
  "{name} turned the match into a museum exhibit of their skills",
  "{name} was making the enemy team's support player support their own therapy",
  "{name} had every spray looking like it was drawn by an artist",
  "{name} was playing like the other team was there as audience",
  "{name} turned every site anchor into a speed bump on the highway",
  "{name} was making the other team's AWPer look like they had a scope cover on",
  "{name} had the match looking like a before and after of the enemy team's confidence",
  "{name} was treating the match like a job and putting in overtime",
  "{name} turned every smoke peek into a surprise party for the enemy",
  "{name} was making the enemy team's default setup look like a suggestion box",
  "{name} had the whole server on their highlight reel",
  "{name} was playing like the killfeed was a personal diary",
  "{name} turned every retake kit into a comeback special",
  "{name} was making the enemy team wonder what game they actually queued for",
  "{name} had the round timer running scared",
  "{name} was treating every duel like a sponsorship opportunity",
  "{name} turned the entire match into a scouting report for pro teams",
  "{name} was making the other team's warmup look like their peak",
  "{name} had every headshot looking like it was written in the script",
  "{name} was playing like the server owed them money and today was payday",
  "{name} turned every after-plant into a Netflix series about patience",
  "{name} was making the other team's flashes look like flashlights",
  "{name} had the match feeling like a farewell tour for the enemy's elo",
  "{name} was treating every round like it came with a signing bonus",
  "{name} turned every lurk into a horror movie for the enemy",
  "{name} was making the other team's site retakes look like a field trip",
  "{name} had the scoreboard looking like it was written by a ghostwriter",
  "{name} was playing like the enemy's smoke lineups were decorative",
  "{name} turned every pistol force into a full buy energy",
  "{name} was making the other team's anchor plays look like anchors in the ocean",
  "{name} had the match looking like an ad for gaming peripherals",
  "{name} was playing like the replay was already trending",
  "{name} turned every frag into a stamp on a passport to victory",
  "{name} was making the other team's coordination look like a flash mob gone wrong",
  "{name} had the enemy questioning if the map was even real",
  "{name} was treating the bomb plant like a formality they graciously allowed",
  "{name} turned every spray down into a calligraphy lesson",
  "{name} was making the other team's timeout calls look like surrender negotiations",
  "{name} had the server running their personal brand",
  "{name} was playing like the minimap was a personal GPS to frags",
  "{name} turned every rotating enemy into a gift-wrapped frag",
  "{name} was making the enemy team's positioning look like modern art",
  "{name} had every angle covered like a security system with feelings",
  "{name} was treating the match like a podcast and they were the only guest",
  "{name} turned every fake into an Oscar-worthy performance",
  "{name} was making the enemy team's A split look like they split up to lose faster",
  "{name} had the match looking like a how-to guide for fraggers",
  "{name} was playing like the match had a laugh track and they were the joke writer",
  "{name} turned every callout into a prediction that aged perfectly",
  "{name} was making the other team's economy look like a documentary about poverty",
  "{name} had the server on a first-name basis",
  "{name} was treating the scoreboard like a personal resume builder",
  "{name} turned the entire other team into content creators of their own lowlights",
  "{name} was making the map look like it was custom-built for them",
  "{name} had the match looking like the pilot episode of a dominance series",
  "{name} was playing like every kill came with a receipt and a thank you note",
  "{name} turned every site take into an eviction notice",
  "{name} was making the other team reconsider the meaning of teamwork",
  "{name} had the lobby feeling like a private server with uninvited guests",
  "{name} was playing like the other team's economy was a charity they funded",
  "{name} turned every HE grenade into a farewell card",
  "{name} was making the other team's rotations look like they were following a broken GPS",
  "{name} had the match feeling like it needed closing credits with their name first",
  "{name} was treating every flash bang like a red carpet entrance",
  "{name} turned every push into a grand opening ceremony",
  "{name} was making the other team's IGL look like they were coaching a little league team",
  "{name} had the server thinking about awarding a medal",
  "{name} was playing like the other team was running a scrimmage against themselves",
  "{name} turned every round into a signed limited edition performance",
  "{name} was making rotations look like a choreographed sequence",
  "{name} had the kill feed scrolling like end credits",
  "{name} was playing like they had admin commands enabled",
  "{name} turned every trade situation into a freebie",
  "{name} was making the other team's flank routes look like surrender paths",
  "{name} had the lobby running replays before the match ended",
  "{name} was playing like every angle was a gift-wrapped opportunity",
  "{name} turned the other team's utility into background effects",
  "{name} was making the other team's communication sound like panic calls",
  "{name} had the server considering a highlight notification",
  "{name} was treating mid-round rotations like a stroll through the park",
  "{name} turned every headshot into a bookmark in the match history",
  "{name} was making the other team's aggression look suicidal",
  "{name} had the lobby feeling like a showcase match",
  "{name} was playing like their aim was filed under 'perfect' in the dictionary",
  "{name} turned every clutch into a casual Tuesday",
  "{name} was making the other team's buy rounds look like eco rounds",
  "{name} had the match sealed before halftime was a discussion",
  "{name} was playing like the other team was warming up and never got warm",
  "{name} turned every entry frag into a front-page story",
  "{name} was making the lobby feel like it was their living room",
  "{name} had every enemy rotation looking like they were running toward their own demise",
  "{name} was treating every site take like they had the key to the front door",
  "{name} turned the enemy's aggression into their own highlight reel",
  "{name} was making every angle look like it was built for them specifically",
  "{name} had the match feeling like a demonstration at a gaming convention",
  "{name} was playing like the server had a dress code and only they were in uniform",
  "{name} turned every eco frag into a headline",
  "{name} was making the other team's strats look like first drafts",
  "{name} had every kill looking like it was choreographed by a director",
  "{name} was treating the match like a level they'd beaten a thousand times",
  "{name} turned every round into a lap around the victory track",
  "{name} was making the scoreboard look like a solo act",
  "{name} had the lobby wondering if it was a prank show starring them as victims",
  "{name} was playing like every bullet was hand-delivered",
  "{name} turned the match into a compilation video before it even ended",
  "{name} was making the other team's defaults look like suggestions for how to lose",
  "{name} had the server on speed dial for future bookings",
  "{name} was treating the match like they had insider knowledge of every round",
  "{name} turned every HE nade into a registered letter of destruction",
  "{name} was making the other team's confidence look borrowed and overdue",
  "{name} had every angle on lockdown like it had a security deposit",
  "{name} was playing like the match was a formality and the trophy was already engraved",
  "{name} turned the enemy team into a stepping stone with feelings",
  "{name} was making every peek look like a drive-through window at a frag restaurant",
  "{name} had the match sealed, stamped, and mailed before overtime was on the table",
  "{name} was treating every kill like a stamp on a passport to the next rank",
  "{name} turned the enemy team's strats into a museum of what not to do",
  "{name} was making every gunfight look like they brought a cheat code and the code was skill",
  "{name} had the server wondering if matchmaking made a mistake in their favor",
  "{name} was playing like every round was scripted and they were the scriptwriter",
  "{name} turned the match into a one-person show with a captive audience of nine",
  "{name} was making the enemy team look like they were playing their first placement match",
  "{name} had every spray looking like it was painted by a robot with perfect calibration",
  "{name} was treating the scoreboard like their personal leaderboard and everyone else was a guest",
  "{name} turned every round win into a chapter of a book the enemy never wanted to read",
  "{name} was making the other team's site holds look like welcome mats with a bow on top",
  "{name} had the match feeling like a documentary and they were the only subject worth filming",
  "{name} was playing like the server was running a personal highlight service just for them",
  "{name} turned the entire match into a resume bullet point",
  "{name} was making the other team question whether they had even warmed up today",
  "{name} had every round feeling like the conclusion of an argument they already won",
  "{name} was treating the lobby like a revolving door of opportunities",
  "{name} turned the match into proof that one player can carry a civilization",
  "{name} was making the other team's hope look like a candle in a hurricane",
  "{name} had the server running overtime just to process all their highlights",
  "{name} was playing like the match was already in the history books and they were the author",
  "{name} turned every interaction into a masterclass the enemy paid tuition for",
  "{name} was making every duel look like the other person showed up to the wrong address",
  "{name} had the lobby feeling like a private concert where only the audience was suffering",
  "{name} was treating the match like a warm bath of domination",
  "{name} turned the other team's game plan into a suggestion they politely declined",
  "{name} was making the server blush with the quality of their performance",
  "{name} had every enemy player looking like they were there for moral support only",
  "{name} was playing like the match was a love letter to their own skill and the enemy read it crying",
  "{name} turned every round into the kind of clip that breaks the internet for exactly one hour",
  "{name} was making the other team's attempts look like auditions they didn't get callbacks for",
  "{name} had the lobby speechless and the scoreboard doing all the talking",
  "{name} was playing like they had rehearsed this exact match in their sleep",
  "{name} turned the enemy team into an audience for a show they didn't buy tickets to",
  "{name} was making every clutch look like the expected outcome",
  "{name} had the match on a leash and took it for a walk through victory lane",
  "{name} was treating every round like a personal invitation to dominate",
  "{name} turned the scoreboard into a shrine to their own performance",
  "{name} was making the enemy team's timeout calls look like intermissions at a play about losing",
  "{name} had every frag looking like it was destined from the character select screen",
  "{name} was playing like the match had a plot and they were the protagonist with no sequel needed",
  "{name} turned the entire server into a stage and everyone else was the supporting cast",
  "{name} was making the other team's setup look like furniture in a house they just bought",
  "{name} had the match feeling like a speedrun world record that nobody asked for but everyone witnessed",
  "{name} was treating every kill like a deposit into a bank account of greatness",
  "{name} turned the match into a seminar and the enemy team was there involuntarily",
  "{name} was making the other team's existence on the server feel like a clerical error",
  "{name} had the lobby feeling like a private screening of their greatest hits",
  "{name} was playing like the server was a stage, the match was the play, and the enemy was the punchline",
];

const ROAST_LINES = [
  "{name} was the team's emotional support",
  "{name} brought good vibes instead of aim",
  "{name} was just there for the company",
  "At least {name} had fun... right?",
  "{name} played like their monitor was off",
  "{name} contributed moral support",
  "{name} was busy admiring the map design",
  "{name} brought snacks instead of frags",
  "{name} was lagging in spirit",
  "{name} had a nice workout pressing W",
  "{name} was sightseeing on the map",
  "{name} mistook this for a walking simulator",
  "{name} was providing valuable intel... to the enemy",
  "{name} was playing on a steering wheel",
  "{name} was in the lobby for warmth",
  "{name} was on a strict no-frag diet",
  "{name} was playing hide and seek without the hide part",
  "{name} turned every duel into a charity donation",
  "{name} was trying to win with positive body language",
  "{name} looked allergic to the scoreboard",
  "{name} was buffering in real time",
  "{name} was serving warm-up vibes in a live match",
  "{name} made bottom frag look like a calling",
  "{name} was testing if helmets really work",
  "{name} was collecting deaths like loyalty points",
  "{name} had more footsteps than impact",
  "{name} was roleplaying a free kill",
  "{name} entered sites like they forgot the flash at home",
  "{name} was making the minimap feel crowded",
  "{name} had a long-term lease in spectator mode",
  "{name} was playing every round on hard mode by choice",
  "{name} was donating aim data to science",
  "{name} made recoil control look optional",
  "{name} was committed to the bit, unfortunately the bit was losing",
  "{name} was out there building character instead of stats",
  "{name} played like the keyboard was upside down",
  "{name} had more deaths than the match had rounds",
  "{name} was speedrunning the respawn screen",
  "{name} was practicing dying",
  "{name} was the first to die and the last to learn",
  "{name} played like they were holding the mouse backwards",
  "{name} brought a knife to a gunfight unironically",
  "{name} was auditioning for the enemy team",
  "{name} made the bot replacement look tempting",
  "{name} was loading into the wrong decade of skill",
  "{name} had the reaction time of a screensaver",
  "{name} was playing like the crosshair was a suggestion",
  "{name} was just there to fill the server capacity",
  "{name} was the team's dedicated content creator for the enemy highlights",
  "{name} played like they were still in the loading screen",
  "{name} made the enemy AWPer feel like a pro player",
  "{name} was cosplaying as a decoy grenade",
  "{name} had the game sense of a roomba",
  "{name} was the team's participation trophy",
  "{name} treated every round like it was a warmup",
  "{name} was playing like they were researching the death animation",
  "{name} made the kill feed look one-sided and it wasn't their side",
  "{name} was operating at peak confusion",
  "{name} had the spatial awareness of a closed door",
  "{name} was the reason the enemy's economy recovered",
  "{name} was playing like the buy menu was a mystery",
  "{name} had the aim of someone trying to draw a circle with an etch-a-sketch",
  "{name} was practicing the art of getting shot first",
  "{name} was playing on a dream and a prayer, mostly prayer",
  "{name} was contributing to the other team's K/D",
  "{name} treated grenades like confetti at their own funeral",
  "{name} was playing like the callouts were in a foreign language",
  "{name} had the positioning of a traffic cone in the wrong lane",
  "{name} was a free kill with a microphone",
  "{name} was collecting death timers like Pokemon cards",
  "{name} was the team's designated seat warmer",
  "{name} was playing like they queued for a different match",
  "{name} had the aim of a garden sprinkler",
  "{name} was one step behind the enemy and two steps behind the team",
  "{name} was treating every peek like a trust fall with the enemy",
  "{name} made every round feel like a 4v5",
  "{name} was providing the enemy team with confidence boosts",
  "{name} played like their sensitivity was set to random",
  "{name} was the team's built-in handicap",
  "{name} was running into sites like a roomba hitting walls",
  "{name} had the game sense of someone who just installed",
  "{name} was basically a mobile health kit for the enemy",
  "{name} was playing like they had money on the other team",
  "{name} treated the AK like a stapler",
  "{name} was fighting the recoil pattern and losing",
  "{name} played like the crosshair was there for decoration",
  "{name} was practicing their spectator mode reflexes",
  "{name} entered every gunfight like they forgot to bring the gun",
  "{name} was playing like the smoke was a suggestion to walk through",
  "{name} had the positioning of someone who learned from the wrong tutorial",
  "{name} was the enemy team's MVP",
  "{name} made every rotate look like a scenic tour",
  "{name} was there in body but not in frags",
  "{name} played like their config was from 2014",
  "{name} was the team's crisis actor for losing situations",
  "{name} was giving the enemy free weapons every round",
  "{name} had the timing of someone walking into a joke late",
  "{name} was playing like they thought it was co-op with the enemy",
  "{name} made every buy round feel like a force buy",
  "{name} was the team's designated viewer",
  "{name} played like the minimap was a screensaver",
  "{name} was running into crossfires like they were turnstiles",
  "{name} had the decision-making of a coin flip that always landed wrong",
  "{name} was playing like they were trying to pad the enemy's stats",
  "{name} made the team's economy look generous with the donations",
  "{name} was treating every flashbang like a personal light show",
  "{name} had the crosshair placement of someone looking at the floor for change",
  "{name} was playing like the round was a surprise party and they were always surprised",
  "{name} was the team's built-in difficulty slider",
  "{name} made every 5v4 feel like a 4v5",
  "{name} was providing the enemy with a warm welcome every round",
  "{name} played like their mouse had a mind of its own and it wasn't a good mind",
  "{name} was the team's resident clip generator for the enemy",
  "{name} had more deaths than the enemy had bullets used efficiently",
  "{name} was playing like they were doing a charity stream for the other team",
  "{name} treated every round like a speed run to the death screen",
  "{name} was the team's human decoy",
  "{name} made every flash peek look like a flash surrender",
  "{name} was giving out free entries like a coupon book",
  "{name} had the utility usage of someone who didn't buy utility",
  "{name} was playing like they were on the wrong side of a highlight reel",
  "{name} made the economy crash by dying with the AWP every round",
  "{name} was the team's unpaid intern",
  "{name} had the positioning of someone who read the map upside down",
  "{name} was playing like the enemy had their screen",
  "{name} treated every smoke like a doorway",
  "{name} was the reason the team called a timeout",
  "{name} played like the bomb timer was a mystery",
  "{name} was providing a public service to the other team's highlights",
  "{name} had the peeking style of someone who's never met a corner before",
  "{name} was playing like the headshot multiplier was turned off",
  "{name} made every clutch situation by being the first to die",
  "{name} was donating weapons to the enemy like it was tax-deductible",
  "{name} had the movement of someone who just discovered WASD",
  "{name} was the enemy team's biggest fan based on contributions",
  "{name} played like their headset was playing music instead of game audio",
  "{name} was treating every angle like a meet-and-greet with the enemy",
  "{name} made every retake impossible by dying in the worst position",
  "{name} was the team's dedicated sacrifice and nobody asked for one",
  "{name} had the spray pattern of a garden hose on full blast",
  "{name} was playing like the server was haunted and they were the ghost",
  "{name} made every anti-eco look competitive for the wrong reasons",
  "{name} was treating every duel like they were testing their reflexes and always failing",
  "{name} had the clutch potential of a wet paper bag",
  "{name} was playing like the kill feed was a spectator-only feature",
  "{name} made every teammate's stats look better by comparison",
  "{name} was the control group in an experiment about aim",
  "{name} treated every round like they were speedrunning to spectator mode",
  "{name} had the flick aim of someone using a trackpad on a moving bus",
  "{name} was playing like they thought they were on the enemy's team",
  "{name} made every save round personal by dying with the bomb",
  "{name} was the team's designated bait and nobody set the trap",
  "{name} had the comms of someone who's always describing how they died",
  "{name} was playing like the scoreboard was counting someone else's stats",
  "{name} made the team's strats look bad by executing them incorrectly every time",
  "{name} was treating the match like a tutorial they couldn't pass",
  "{name} had the awareness of someone who tabs out between rounds and doesn't tab back in",
  "{name} was the team's consistent player in consistently dying first",
  "{name} made every trade kill impossible by dying in Narnia",
  "{name} was playing like the other team had their playbook",
  "{name} had the weapon management of someone who shops at the wrong section",
  "{name} was treating every CT round like the T side was optional",
  "{name} made the team's utility look like fireworks for the enemy's celebration",
  "{name} was the team's tour guide through the map's respawn areas",
  "{name} had the post-plant positioning of someone who forgot the bomb was down",
  "{name} was playing like the money system was there to confuse them",
  "{name} made every pistol round look like a knife round on accident",
  "{name} was the reason the team's average ADR had a decimal point",
  "{name} had the defuse awareness of someone who thinks the beeping is music",
  "{name} was playing like they had a personal rivalry with their own team's chances",
  "{name} made every teammate's job harder by existing on the server",
  "{name} was providing the enemy with a predictable pattern: die, respawn, die",
  "{name} had the first-bullet accuracy of a warning shot that warned the wrong people",
  "{name} was the team's designated not-in-the-right-place-at-any-time",
  "{name} made every flash assist count by blinding themselves",
  "{name} was playing like they pre-aimed every angle the enemy wasn't at",
  "{name} had the economy management of someone who buys a negev on pistol round",
  "{name} was the team's human smoke grenade: confusing but not for the enemy",
  "{name} made every round a learning experience and learned nothing",
  "{name} was playing like the game had friendly fire and they were the target",
  "{name} had the rotation speed of continental drift",
  "{name} was the team's emotional support player and even that wasn't working",
  "{name} made every bomb plant look like a miracle because they almost ruined it",
  "{name} was providing the server with entertainment at their own expense",
  "{name} had the aim style of someone who closes their eyes and hopes for the best",
  "{name} was playing like the enemy team was invisible and only walls were threats",
  "{name} made the team miss having a bot replacement as an option",
  "{name} was the scoreboard's basement resident",
  "{name} had the positioning of someone reading a different callout sheet",
  "{name} was playing like the AWP was a very expensive telescope",
  "{name} made every smoke execute easier by dying before it started",
  "{name} was the team's dedicated info gatherer except the info was always too late",
  "{name} had the game IQ of a goldfish with amnesia",
  "{name} was playing like every corner held a birthday surprise from the enemy",
  "{name} made every strat call irrelevant by dying in the setup phase",
  "{name} was treating the match like they had nine lives and used them all in round one",
  "{name} had the trigger discipline of someone who forgets they have a trigger",
  "{name} was the team's resident map explorer who only explored respawn",
  "{name} made every save round a full save by dropping their weapon for the enemy",
  "{name} was playing like the scoreboard was upside down and they were winning",
  "{name} had the confidence of a top fragger and the stats of a spectator",
  "{name} was the team's wildcard and the wild part was losing every fight",
  "{name} made every force buy a waste by dying before shooting",
  "{name} was treating every molotov like a suggestion to stand still",
  "{name} had the clutch gene of a pair of jeans with no pockets",
  "{name} was playing like their team's strats were written in invisible ink",
  "{name} made every timeout feel necessary",
  "{name} was the team's dedicated angle holder who held the wrong angle every time",
  "{name} had the smoke usage of someone who forgot which button throws it",
  "{name} was playing like they were speedrunning the wrong game",
  "{name} made every eco round an eco round for both teams",
  "{name} was providing the enemy with free ADR like a public utility",
  "{name} had the movement of a chess piece that can only move backwards",
  "{name} was treating every gunfight like a polite conversation that ended badly",
  "{name} made the team consider tactical pauses just to strategize around them",
  "{name} was the team's free agent and nobody wanted to sign them",
  "{name} had the impact of a dropped flashbang that rolled under the team",
  "{name} was playing like the game's difficulty was set to nightmare for them only",
  "{name} made every site hold a revolving door for the enemy",
  "{name} was treating the scoreboard like it was someone else's problem",
  "{name} had the recoil control of someone arm-wrestling during a gunfight",
  "{name} was the team's resident surprise: always surprisingly dead",
  "{name} made every trade attempt a solo queue experience for the rest of the team",
  "{name} was playing like the bomb was a hot potato and they were always it",
  "{name} had the peek timing of someone who shows up after the fight is over",
  "{name} was the team's dedicated flashbang target practice for the enemy",
  "{name} made every round a 4v5 with extra steps",
  "{name} was providing the enemy with opening frags like a subscription service",
  "{name} had the map knowledge of someone who took a wrong turn three rounds ago",
  "{name} was treating the match like an extended lobby warmup",
  "{name} made the enemy team's confidence grow with every interaction",
  "{name} was the team's resident mystery: what were they thinking",
  "{name} had the flash timing of someone who throws after the push already failed",
  "{name} was playing like every round was their first round ever",
  "{name} made the team's comms worse by constantly calling out their own deaths",
  "{name} was the team's built-in excuse for why they lost",
  "{name} had the aggression of a player with no ammo and no plan",
  "{name} was treating the match like they were being paid to lose and overpaid",
  "{name} made every smoke push scarier for their own team than the enemy",
  "{name} was the enemy team's comfort pick",
  "{name} had the awareness of someone playing with their back to the monitor",
  "{name} was playing like the only callout they knew was 'help'",
  "{name} made every timeout less about strategy and more about coping",
  "{name} was treating each round like a new opportunity to disappoint",
  "{name} had the fragging power of a stern look",
  "{name} was the team's pet project that never shipped",
  "{name} made the lobby feel like a 9v1 with them as the spectator",
  "{name} was playing like they queued for casual and ended up in ranked by accident",
  "{name} had the game sense of a loading screen tip that was wrong",
  "{name} was the team's designated holder of W and nothing else",
  "{name} made every execute look under-staffed",
  "{name} was providing the enemy team's AWPer with free scope practice",
  "{name} had the movement of someone still learning that shift exists",
  "{name} was treating the match like an adventure and every adventure ended in death",
  "{name} made the team's highlight reel an argument for solo queue",
  "{name} was the team's anchor in the sense that they dragged everything down",
  "{name} had the spray control of someone trying to write their name with a fire hose",
  "{name} was playing like every kill was a boss fight they weren't leveled for",
  "{name} made the enemy team's eco frags look like ace clips",
  "{name} was the team's dedicated atmosphere player",
  "{name} had the positioning of someone who peaked in the tutorial",
  "{name} was treating every gunfight like a coin flip where they always called wrong",
  "{name} made the team dream about what having five players would feel like",
  "{name} was the map's least valuable landmark",
  "{name} had the impact of a decoy grenade that nobody noticed",
  "{name} was playing like the respawn timer was the actual game",
  "{name} made every site take a prayer session for the team",
  "{name} was providing the enemy with ego boosts like a motivational speaker",
  "{name} had the first kill potential of a sleeping guard",
  "{name} was the team's reason for the post-match therapy bill",
  "{name} made every 4v5 a callback to a recurring theme",
  "{name} was treating every smoke like a suggestion to run through it eyes closed",
  "{name} had the utility impact of someone who bought a kit but forgot to defuse",
  "{name} was the team's one-player audience during clutch rounds",
  "{name} made the team's rating gap look like a canyon",
  "{name} was playing like the scoreboard was written in a language they couldn't read",
  "{name} had the lurk success rate of a doorbell camera with the battery dead",
  "{name} was treating the match like an open-world game with no objectives",
  "{name} made the enemy team feel like smurfs without changing accounts",
  "{name} was the team's designated background noise",
  "{name} had the site anchor skills of someone who forgot which site they were on",
  "{name} was playing like the enemy had a personal invitation to find them",
  "{name} made every round loss feel like a team-building exercise in disappointment",
  "{name} was treating the AK spray like abstract art that nobody asked for",
  "{name} had the trading ability of someone who shows up to the swap meet empty-handed",
  "{name} was the team's unofficial mascot for losing",
  "{name} made the enemy team's worst player look like a star",
  "{name} was playing like the server had different rules just for them and all the rules were lose",
  "{name} had the match impact of elevator music",
  "{name} was treating every flash like a disco ball for the enemy team's dance party",
  "{name} made every post-plant look hopeless and they weren't even alive for it",
  "{name} was the team's expert in finding new ways to die",
  "{name} had the timing of someone who arrives at a party as it's ending",
  "{name} was playing like the match was already over and they were right but for the wrong reasons",
  "{name} made the team miss the days when they played with four people on purpose",
  "{name} was the enemy team's daily quest: completed automatically",
  "{name} had the pre-aim of someone who heard a callout from three rounds ago",
  "{name} was treating the match like practice for a different game entirely",
  "{name} made the team's callouts less useful because every callout ended with '{name} is dead'",
  "{name} was the lobby's participation award holder",
  "{name} had the confidence of someone who peaked in casual and never came down",
  "{name} was playing like the enemy knew where they were because {name} told them",
  "{name} made every gun round feel like a pistol round for the team",
  "{name} was the team's dedicated test subject for the enemy's util lineups",
  "{name} had the round impact of a bystander who walked into the server by accident",
  "{name} was treating the scoreboard like fiction",
  "{name} made every strat depend on not depending on {name}",
  "{name} was the team's backup plan that was somehow also the first to fail",
  "{name} had the crosshair placement of someone who heard 'aim high' and looked at the sky",
  "{name} was playing like the match was a fever dream and they were the fever part",
  "{name} made the team consider a 4-stack next time",
  "{name} was the enemy's personal highlight reel cinematographer",
  "{name} had the callout accuracy of someone who mixes up A and B",
  "{name} was treating the match like a documentary about their own struggles",
  "{name} made every clutch impossible by setting it up wrong from the start",
  "{name} was the team's dedicated loss condition",
  "{name} had the fragging output of a pacifist on principle",
  "{name} was playing like the round started when they died and ended when they respawned",
  "{name} had the trade potential of someone who brought an empty bag to a swap meet",
  "{name} was treating every entry like a personal sacrifice nobody asked for",
  "{name} made the team's average rating look like a math problem",
  "{name} was the team's dedicated angle-vacater",
  "{name} had the bomb awareness of someone who forgot the objective was a thing",
  "{name} was playing like the other team had a bounty on them and collected early",
  "{name} made the team wish friendly fire was enabled so they could put them out of their misery",
  "{name} was treating every CT hold like an open-door policy",
  "{name} had the reaction speed of a dial-up connection in 2004",
  "{name} was the team's designated first death and took the job too seriously",
  "{name} made the team's T side look like a protest march with casualties",
  "{name} was playing like the defuse kit was a myth they didn't believe in",
  "{name} had the game plan of someone who read the map legend wrong",
  "{name} was treating the AWP like a very expensive binoculars",
  "{name} made every stack look unstacked by walking through it alone",
  "{name} was the team's dedicated economy drain and they never called in sick",
  "{name} had the peek style of someone who announces their arrival by dying",
  "{name} was playing like the HE grenade was self-targeted",
  "{name} made the team's CT side look like a welcome committee for the enemy",
  "{name} was the team's dedicated morale dampener and business was booming",
  "{name} had the post-plant strategy of dying before the bomb was even down",
  "{name} was treating the match like community service they were court-ordered to attend",
  "{name} made the enemy team's worst player look competent by comparison",
  "{name} was the team's one-person evidence of why matchmaking needs fixing",
  "{name} had the smoke awareness of someone who treats every smoke like a hallway to walk through",
  "{name} was playing like they had a personal bet against their own team",
  "{name} made the team's mid-round calls irrelevant because they were already dead by then",
  "{name} was the team's dedicated space-taker in the sense that they took up a player slot",
  "{name} had the fragging consistency of a broken vending machine",
  "{name} was treating the match like an escape room and they only found the exit through death",
  "{name} made the enemy's entry fragger look like a genius because {name} was always the entry",
  "{name} was the team's designated info player but the only info they gave was where not to die",
  "{name} had the timing of someone who checks their phone mid-round",
  "{name} was playing like every round was a fresh chance to make the same mistake",
  "{name} made the team's scoreboard look like it had a typo in their column",
  "{name} was the team's resident expert in getting wallbanged from new angles",
  "{name} had the site hold of someone who set up lawn chairs for the enemy",
  "{name} was treating the round like a vacation that always ended at the same resort: death",
  "{name} made the team's chances look like a math equation where they were the negative number",
  "{name} was the team's most reliable player if you needed someone to die on schedule",
  "{name} had the crosshair on a sightseeing tour of everything except the enemy",
  "{name} was playing like the only strat they practiced was 'lose duel instantly'",
  "{name} made the team's execute look like a group project where one person did nothing",
  "{name} was the enemy team's favorite opponent and they didn't even know it yet",
  "{name} had the lurk game of someone who lurked in the wrong dimension",
  "{name} was treating the scoreboard like an abstract concept that didn't apply to them",
  "{name} made the team consider tactical formations that didn't include them",
  "{name} was the team's dedicated morale test and everyone failed",
  "{name} had the movement speed of someone carrying invisible furniture",
  "{name} was playing like the match had a B-plot and they were the comic relief that wasn't funny",
  "{name} made the team's CT setup look like it had a hole shaped exactly like them",
  "{name} was the team's designated reason for the enemy team's confidence boost",
  "{name} had the flash usage of someone who bought them for the light effects",
  "{name} was treating the match like a buffet where they were the main course for the enemy",
  "{name} made every round feel like a pop quiz they didn't study for",
  "{name} was the team's consistent contribution to the enemy's economy through weapon donations",
  "{name} had the aim trajectory of someone drawing circles in a windstorm",
  "{name} was playing like every callout was a suggestion they politely ignored",
  "{name} made the team's rotation look chaotic because they were rotating to death every time",
  "{name} was the team's designated holder of L's and had a full collection",
  "{name} had the site presence of a ghost that forgot how to be scary",
  "{name} was treating the match like a social experiment about losing gracefully",
  "{name} made the team's economy look like a charity drive for the enemy's weapon fund",
  "{name} was the team's human proof that not all heroes wear capes, some just feed",
  "{name} had the dueling record of someone who challenges people to staring contests and blinks first",
  "{name} was playing like the death screen had better content than being alive",
  "{name} made the team's strat book look incomplete because the chapter about them said 'just don't'",
  "{name} was the team's reminder that not every queue dodge is a waste of time",
  "{name} had the round presence of background music that nobody noticed was playing",
  "{name} was treating every angle like an opportunity to discover a new way to lose a duel",
  "{name} made the team's timeout calls feel like group therapy sessions about acceptance",
  "{name} was the team's proof that sometimes the real enemy is on your side",
  "{name} had the spray pattern of someone writing an apology letter mid-firefight",
  "{name} was playing like the match was a field trip and they were the kid who got lost",
  "{name} made the team's map control look like a territory dispute they were losing to a ghost",
  "{name} was the team's one guaranteed constant: a death in the opening seconds",
  "{name} had the adaptability of someone who makes the same mistake with renewed enthusiasm",
  "{name} was treating the match like a meditation retreat that involved a lot of spectating",
  "{name} made the team's communication worse because every callout ended with 'and {name} is dead again'",
  "{name} was the team's dedicated test dummy for the enemy's new strats",
  "{name} had the second-round impact of someone who forgot the first round happened",
  "{name} was playing like the only button on their keyboard was the one that says 'give up'",
  "{name} made the team's highlight reel shorter by providing zero content to include",
  "{name} was the team's living, dying proof that heart can't replace aim",
  "{name} had the bomb plant success rate of someone who thinks the bomb is decorative",
  "{name} was treating the lobby like a waiting room where they waited to lose",
  "{name} made the enemy team's task so easy they probably alt-tabbed between rounds",
  "{name} was the team's unofficial surrender vote that counted every round",
  "{name} had the money management of someone who tips the enemy with their weapon drop",
  "{name} was playing like the ranking system owed them a refund",
  "{name} made the team dream of a world where they had a real fifth player",
  "{name} was the team's designated bottom of every stat column",
  "{name} had the entry success of someone who knocks on the door and waits for the enemy to answer with a headshot",
  "{name} was treating the match like volunteer work and they volunteered to lose",
  "{name} was the scoreboard's special guest in the comedy section",
  "{name} had the info gathering skills of someone who dies before seeing anything useful",
  "{name} was playing like the enemy had a radar hack and it was just their own bad positioning",
  "{name} made the team's chances drop faster than their own HP in every round",
  "{name} was the enemy team's daily dose of serotonin",
  "{name} had the combat effectiveness of a decoy that doesn't even make noise",
  "{name} was treating every peek like an audition they bombed",
  "{name} made the team's average kills per round a rounding error",
  "{name} was the team's unofficial cheerleader from the spectator cam",
  "{name} had the survival instinct of a lemming with a blindfold",
  "{name} was playing like the kill count was someone else's responsibility",
  "{name} made the team wonder if the server had a minimum player requirement they weren't meeting",
  "{name} was the team's walking talking lesson in why stats matter",
  "{name} had the combat presence of a closed book in a library nobody visits",
  "{name} was treating every site hold like a reservation they forgot to confirm",
  "{name} made the enemy team's stats look inflated and it was all {name}",
  "{name} was the team's permanent resident of the bottom frag zip code",
  "{name} had the aggression of a question mark in a room full of exclamation points",
  "{name} was playing like the enemy had a sniper trained on their spawn point",
  "{name} made the team's comms feel like a eulogy for their own chances every round",
  "{name} was the team's designated sacrificial lamb but the sacrifice never helped",
  "{name} had the peeking confidence of someone who thinks they're invisible",
  "{name} was treating the scoreboard like a number they'd rather not call",
  "{name} made the enemy team comfortable enough to force buy every round",
  "{name} was the team's reminder that heart alone doesn't win gunfights",
  "{name} had the post-death commentary of someone who always had a better plan after dying",
  "{name} was playing like the match was a group assignment and they chose to observe",
  "{name} made the team's round wins feel miraculous because they happened despite {name}",
  "{name} was the team's permanent occupant of the 'room for improvement' category",
  "{name} had the combat contribution of a spectator who accidentally got a player slot",
  "{name} was treating every duel like a formality they lost on purpose",
  "{name} made the enemy's eco rounds feel like full-buy rounds because they always found {name} first",
  "{name} was the team's proof that not every player counts equally on the scoreboard",
  "{name} had the kill timing of someone who arrives after every fight like a concerned neighbor",
  "{name} was playing like their monitor showed a different match than everyone else's",
  "{name} made the team's chance of winning correlate directly with whether {name} was alive",
  "{name} was the team's one-person argument for smaller team sizes",
  "{name} had the rotations of someone following a GPS that recalculates to death",
  "{name} was treating every flash like a personal spotlight that attracted enemy fire",
  "{name} made the team's strats feel like they were designed around avoiding {name}",
  "{name} was the team's reason for the post-match block button",
  "{name} had the aim of someone who practices by shooting at the sky",
  "{name} was playing like the match was a dream and the alarm went off every round",
  "{name} made the team's hope look like a bar graph that only went down",
  "{name} was the team's permanent subscriber to the death notification channel",
  "{name} had the utility usage of someone who throws everything at their own feet",
  "{name} was treating the match like an interactive movie where they always chose wrong",
  "{name} made the enemy team's worst round still include a free kill on {name}",
  "{name} was the team's personal proof that matchmaking is an imperfect system",
  "{name} had the situational awareness of someone playing with the sound off",
  "{name} was playing like the match was a loyalty program for dying and they had premium status",
  "{name} made the team consider that maybe 4v5 was the real strategy all along",
  "{name} was the team's resident proof that you can load into a match without loading into the gameplay",
  "{name} had the kill participation of someone who was technically on the server",
  "{name} was treating the match like it owed them an apology for existing",
  "{name} made every enemy player look like they were having the game of their life",
  "{name} was the team's reminder that not every player slot comes with a warranty",
  "{name} had the round survival rate of a snowflake in a frying pan",
  "{name} was playing like the game was trying to tell them something and the message was 'stop'",
  "{name} made the team's map control look like a land dispute they'd already lost",
  "{name} was the team's designated filler episode in a match that needed a main character",
  "{name} had the weapon accuracy of someone who bought the wrong sensitivity and stuck with it",
  "{name} was treating every round like a creative writing exercise about new ways to lose",
  "{name} made the team's economic graph look like a rollercoaster designed by someone who hates joy",
  "{name} was the team's walking encyclopedia of bad positions to play from",
  "{name} had the in-game leader potential of someone who leads the team into every bad decision",
  "{name} was playing like the match was a podcast about failure and they were the special guest",
  "{name} made the team's defense look like a suggestion the enemy politely declined",
  "{name} was the team's designated holder of the 'most improved needed' award",
  "{name} had the trading success of someone who shows up after the store closed",
  "{name} was treating the match like a tour of every death spot on the map",
  "{name} made the enemy team's strategy meeting a one-word agenda: find {name}",
  "{name} was the team's proof that loading screen tips needed to be longer",
  "{name} had the flashbang avoidance of someone who looks directly at every flash",
  "{name} was playing like the scoreboard was a golf score where lower is better except it wasn't",
  "{name} made the team reconsider their queue preferences for next time",
  "{name} was the team's dedicated content provider for the enemy's post-match screenshots",
  "{name} had the clutch probability of a lottery ticket in a house fire",
  "{name} was treating the match like an episode they wanted to get cancelled",
  "{name} made the enemy team's weakest link look like the strongest chain in the lobby",
  "{name} was the team's permanent resident of the shadow realm between dead and useful",
  "{name} had the teamplay of someone who thinks team means the enemy team",
  "{name} was playing like the match was a documentary about what not to do and they were the star",
  "{name} made the team's W column look like it had a restraining order against {name}",
  "{name} was the team's designated answer to the question 'what went wrong'",
  "{name} had the match impact of a note left on a fridge that nobody reads",
  "{name} was treating the lobby like a museum exhibit of their worst performances",
  "{name} made the team wish they could trade players mid-match",
  "{name} was the team's exhibit A in the case of 'why we lost'",
  "{name} had the combat efficiency of a spoon in a knife fight",
  "{name} was playing like the match was already decided and their role was background extra",
  "{name} made the team's stats page look like it needed a support group",
  "{name} was the team's permanent answer to 'who died first this round'",
  "{name} had the dueling success of someone who brings a pool noodle to a sword fight",
  "{name} was treating the match like a trust exercise and the trust was misplaced every time",
  "{name} made the enemy team feel like they were playing with an extra teammate they didn't know about",
];

const SESSION_CARRY_LINES = [
  "{name} owned the whole session, not just one map",
  "{name} was the main character all night",
  "{name} carried the party like it was their birthday",
  "The squad owes {name} dinner after that session",
  "{name} was built different today — every single map",
  "{name} didn't just show up, they showed out all session",
  "{name} was on a heater that lasted hours",
  "{name} turned a gaming session into a masterclass",
  "Somebody check {name}'s contract — they went overtime on frags",
  "{name} was the reason the lobby kept queuing",
  "{name} made every map look like their home turf",
  "{name} ran the session like a shift manager at the frag factory",
  "{name} put the team on their back for the whole night",
  "{name} was farming MVPs across multiple time zones",
  "{name} turned the session into a personal highlight tape",
];

const SESSION_ROAST_LINES = [
  "{name} was consistently inconsistent all session",
  "{name} attended every map but participated in none",
  "{name} was the session's designated spectator",
  "{name} brought their C game and it still wasn't enough",
  "At least {name} was there for morale... all night long",
  "{name} set a new personal worst — across multiple maps",
  "{name} was the anchor of the team, and not the good kind",
  "{name} contributed loading screen energy all session",
  "The squad carried {name} like checked luggage",
  "{name} played every map like it was their first time on a mouse",
  "{name} was on a cold streak that could freeze the server room",
  "{name} was the reason the party almost stopped queuing",
  "{name} got their money's worth from the respawn button",
  "{name} had a long night — unfortunately so did the team",
  "{name} was speedrunning the bottom of every scoreboard",
];

function hashMatchId(matchId: string): number {
  let hash = 0;
  for (let i = 0; i < matchId.length; i++) {
    hash = (hash * 31 + matchId.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

export function getBanterLine(
  type: BanterType,
  name: string,
  matchId: string
): string {
  const lines = type === "carry" ? CARRY_LINES : ROAST_LINES;
  const index = hashMatchId(matchId + type) % lines.length;
  return lines[index].replace("{name}", name);
}

export function getBanterCatalogSize(type: BanterType): number {
  return (type === "carry" ? CARRY_LINES : ROAST_LINES).length;
}

export function getSessionBanterLine(
  type: BanterType,
  name: string,
  playerId: string,
  date: string
): string {
  const lines = type === "carry" ? SESSION_CARRY_LINES : SESSION_ROAST_LINES;
  const index = hashMatchId(playerId + date + type) % lines.length;
  return lines[index].replace("{name}", name);
}
